import os
import pathlib
import warnings

import yaml
from md_utils import dict_to_table

import minari
from minari.utils import get_dataset_spec_dict


DATASET_FOLDER = pathlib.Path(__file__).parent.parent.joinpath("datasets")


def _rst_escape(text: str) -> str:
    """Escape text for RST."""
    return text.replace("*", r"\*").replace("_", r"\_").replace("`", r"\`")


def _generate_community_dataset_page(dataset_entry):
    """Generate a dataset page for a community dataset."""
    dataset_id = dataset_entry.get("dataset_id", "")
    display_name = dataset_entry.get("display_name", dataset_id)

    if not dataset_id:
        warnings.warn(f"Skipping dataset entry without dataset_id: {dataset_entry}")
        return

    try:
        # Get metadata from remote datasets first
        remote_datasets = minari.list_remote_datasets(latest_version=True)
        if dataset_id not in remote_datasets:
            warnings.warn(f"Dataset {dataset_id} not found in remote datasets")
            return

        metadata = remote_datasets[dataset_id]

        # Extract description, author, and tags from metadata
        description = metadata.get("description", "")

        # Generate page content with custom title
        content = "---\nautogenerated:\n"
        content += f"title: {display_name}\n"
        content += "---\n\n"
        content += f"# {display_name}\n\n"

        if description:
            content += "## Description\n\n"
            content += description + "\n\n"

        content += "## Dataset Specs\n\n"
        content += dict_to_table(get_dataset_spec_dict(metadata))
        content += "\n\n"

        # Add environment specs if available
        env_spec = metadata.get("env_spec")
        if env_spec is not None:
            content += "## Environment Specs\n\n"
            content += "This environment can be recovered from the Minari dataset as follows:\n\n"
            content += "```python\n"
            content += "import minari\n"
            content += f"dataset = minari.load_dataset('{dataset_id}')\n"
            content += "env = dataset.recover_environment()\n"
            content += "```\n\n"

        # Write dataset page in the same location as regular datasets
        # Save as dataset_id + ".md" (same pattern as gen_dataset_md.py)
        dataset_md_path = DATASET_FOLDER.joinpath(dataset_id + ".md")
        os.makedirs(os.path.dirname(dataset_md_path), exist_ok=True)

        with open(dataset_md_path, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"Generated community dataset page for {dataset_id}")

    except Exception as e:
        warnings.warn(f"Failed to generate page for {dataset_id}: {e}")


def generate_community_page(
    yaml_path=DATASET_FOLDER.joinpath("community", "community.yaml"),
    out_rst=DATASET_FOLDER.joinpath("community", "index.rst"),
):
    if not os.path.exists(yaml_path):
        print(f"YAML file not found: {yaml_path}")
        return

    with open(yaml_path) as f:
        community_data = yaml.safe_load(f) or []

    # Generate individual dataset pages first
    for dataset_entry in community_data:
        _generate_community_dataset_page(dataset_entry)

    # Generate the index page
    content = "Community Datasets\n"
    content += "==================\n\n"
    content += "Below is a list of datasets contributed by the community. "
    content += "To add yours, open a PR editing ``docs/datasets/community/community.yaml``.\n\n"

    content += ".. raw:: html\n\n"
    content += '    <div class="sphx-glr-thumbnails">\n\n'

    # Get metadata for all datasets to extract descriptions
    remote_datasets = minari.list_remote_datasets(latest_version=True)

    for dataset_entry in community_data:
        dataset_id = dataset_entry.get("dataset_id", "")
        display_name = _rst_escape(dataset_entry.get("display_name", dataset_id))

        # Get description from metadata
        description = ""
        local_url = f"/datasets/{dataset_id}/"  # Set default URL

        if dataset_id in remote_datasets:
            description = _rst_escape(
                remote_datasets[dataset_id].get("description", "")
            )

        # Thumb card - matching tutorial style
        content += ".. raw:: html\n\n"
        tooltip = description if description else display_name
        content += f'    <div class="sphx-glr-thumbcontainer" tooltip="{tooltip}">\n\n'

        content += ".. only:: html\n\n"
        # Default to minari-text.png with width constraint to match tutorial cards
        # Wrap image in link using target directive
        img_src = "/_static/img/minari-text.png"
        content += f"  .. image:: {img_src}\n"
        content += f"    :alt: {display_name}\n"
        content += "    :width: 400px\n"
        content += f"    :target: {local_url}\n\n"

        content += ".. raw:: html\n\n"
        content += f'      <div class="sphx-glr-thumbnail-title">{display_name}</div>\n'
        content += "    </div>\n\n"

    # Add "Add your own dataset" card
    content += ".. raw:: html\n\n"
    content += '    <div class="sphx-glr-thumbcontainer" tooltip="Add your own dataset to this page">\n\n'

    content += ".. only:: html\n\n"
    # Link to README with instructions
    readme_url = "https://github.com/Farama-Foundation/Minari/blob/main/docs/datasets/community/README.md"
    content += "  .. image:: /_static/img/minari-text.png\n"
    content += "    :alt: Add Your Dataset\n"
    content += "    :width: 400px\n"
    content += f"    :target: {readme_url}\n\n"

    content += ".. raw:: html\n\n"
    content += '      <div class="sphx-glr-thumbnail-title">Add Your Dataset</div>\n'
    content += "    </div>\n\n"

    content += ".. raw:: html\n\n"
    content += "    </div>\n\n"

    os.makedirs(os.path.dirname(out_rst), exist_ok=True)
    with open(out_rst, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    generate_community_page()


if __name__ == "__main__":
    main()
