name: Build Documentation website
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  docs:
    name: Generate Website
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
            python-version: '3.9'

      - run: sudo apt-get install xvfb

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Install Minari
        run: pip install .[all]

      - name: Download HF datasets with CLI
        run: |
          huggingface-cli download farama-minari/D4RL --repo-type=dataset --include="*namespace_metadata.json" --local-dir="$HOME/.minari/datasets/D4RL"
          huggingface-cli download farama-minari/minigrid --repo-type=dataset --include="*namespace_metadata.json" --local-dir="$HOME/.minari/datasets/minigrid"
          huggingface-cli download farama-minari/atari --repo-type=dataset --include="*namespace_metadata.json" --local-dir="$HOME/.minari/datasets/atari"
          huggingface-cli download farama-minari/mujoco --repo-type=dataset --include="*namespace_metadata.json" --local-dir="$HOME/.minari/datasets/mujoco"

      - name: Build Datasets Docs
        run: xvfb-run --auto-servernum python docs/_scripts/gen_dataset_md.py

      - name: Build
        run: sphinx-build -b dirhtml -v docs _build

      - name: Remove .doctrees
        run: rm -r _build/.doctrees

      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build
          target-folder: main
          clean: false
