# This workflow will build and (if release) publish Python distributions to PyPI
# For more information see:
#   - https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#   - https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
#

name: Manual Build and Publish
on:
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools build
    - name: Build sdist and wheels
      run: python -m build
    - name: Store wheels
      uses: actions/upload-artifact@v4
      with:
        path: dist

  publish:
    runs-on: ubuntu-latest
    needs:
    - build-wheels
    steps:
    - name: Download dists
      uses: actions/download-artifact@v4
      with:
        name: artifact
        path: dist
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
