name: Manual Docs Versioning
on:
  workflow_dispatch:
    inputs:
      version:
          description: 'Documentation version to create'
          required: true
      commit:
          description: 'Commit used to build the Documentation version (SHA)'
          required: false
      latest:
          description: 'Latest version'
          type: boolean

permissions:
  contents: write
jobs:
  docs:
    name: Generate Website for new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: inputs.commit == ''

      - uses: actions/checkout@v3
        if: inputs.commit != ''
        with:
          ref: ${{ inputs.commit }}

      - uses: actions/setup-python@v4
        with:
            python-version: '3.9'

      - run: sudo apt-get install xvfb

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Install Minari
        run: pip install .[all]

      - name: Download HF datasets with CLI
        run: |
          huggingface-cli download farama-minari/D4RL --repo-type=dataset --include="*namespace_metadata.json" --local-dir="$HOME/.minari/datasets/D4RL"
          huggingface-cli download farama-minari/minigrid --repo-type=dataset --include="*namespace_metadata.json" --local-dir="$HOME/.minari/datasets/minigrid"
          huggingface-cli download farama-minari/atari --repo-type=dataset --include="*namespace_metadata.json" --local-dir="$HOME/.minari/datasets/atari"
          huggingface-cli download farama-minari/mujoco --repo-type=dataset --include="*namespace_metadata.json" --local-dir="$HOME/.minari/datasets/mujoco"

      - name: Build Datasets Docs
        run: xvfb-run --auto-servernum python docs/_scripts/gen_dataset_md.py

      - name: Build
        run: sphinx-build -b dirhtml -v docs _build

      - name: Remove .doctrees
        run: rm -r _build/.doctrees

      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build
          target-folder: ${{ inputs.version }}
          clean: false

      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: inputs.latest
        with:
          folder: _build
          clean-exclude: |
            *.*.*/
            main
